build: off

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: false

build_script:
  - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/limix/hcephes/master/install.bat', 'install.bat')" && install.bat

test_script:
  - if NOT exist "%programfiles%\\hcephes\\lib\\hcephes.lib" exit 1
  - if NOT exist "%programfiles%\\hcephes\\bin\\hcephes.dll" exit 1
  - if NOT exist "%programfiles%\\hcephes\\lib\\hcephes_static.lib" exit 1
  - if NOT exist "%programfiles%\\hcephes\\include\\hcephes.h" exit 1
