os:
  - linux
  - osx
language: c
sudo: required
script:
  - bash <(curl -fsSL https://raw.githubusercontent.com/limix/hcephes/master/install)
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      test -e /usr/local/include/hcephes.h;
      test -e /usr/local/lib/libhcephes.so;
      test -e /usr/local/lib/libhcephes_static.a;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      test -e /usr/local/include/hcephes.h;
      test -e /usr/local/lib/libhcephes.dylib;
      test -e /usr/local/lib/libhcephes_static.a;
    fi
notifications:
  email:
    recipients:
    - danilo.horta@gmail.com
    on_success: change
    on_failure: always
